### ISSUE TITLE
client.domains.all not working

### ISSUE THREAD

**Issue by gregf** [digitalocean/droplet_kit#14] opened 2014-11-10 04:59 UTC
I'm not able to list domains

```ruby
client = DropletKit::Client.new(access_token: token)
client.domains.all.each do |domain|
  puts domain.name
end
```

I always get the following error.

```
/home/gregf/.gem/ruby/2.1.4/gems/droplet_kit-1.1.1/lib/droplet_kit/paginated_resource.rb:62:in `retrieve': no implicit conversion of String into Array (TypeError)
	from /home/gregf/.gem/ruby/2.1.4/gems/droplet_kit-1.1.1/lib/droplet_kit/paginated_resource.rb:54:in `fetch_next_page'
	from /home/gregf/.gem/ruby/2.1.4/gems/droplet_kit-1.1.1/lib/droplet_kit/paginated_resource.rb:26:in `each'
	from -:21:in `<main>'
```

**Comment by science** [comment] 2015-03-18 21:12
I'm getting this error at the moment. Maybe there is something related to api load or something? My code was working fine for weeks, now it's failing with this error. If I call `client.droplets.all.any?` or `.each` I get the same error:
```
TypeError Exception: no implicit conversion of String into Array
```
I'm upgraded to 1.2.0 and it didn't make any difference (I was on 1.1.3). Any thoughts?

**Comment by science** [comment] 2015-03-18 21:14
A little more detail:
```
/usr/local/lib/ruby/gems/2.1.0/gems/droplet_kit-1.2.0/lib/droplet_kit/paginated_resource.rb:68:in `retrieve': no implicit conversion of String into Array (TypeError)
	from /usr/local/lib/ruby/gems/2.1.0/gems/droplet_kit-1.2.0/lib/droplet_kit/paginated_resource.rb:60:in `fetch_next_page'
	from /usr/local/lib/ruby/gems/2.1.0/gems/droplet_kit-1.2.0/lib/droplet_kit/paginated_resource.rb:26:in `each'
	from do-servers-manage.rb:84:in `<main>'
```
Looks pretty similar to the OP's point of error..

**Comment by science** [comment] 2015-03-18 21:21
I added this to the paginated_resource.rb file on line 67
```
puts invoker.handle_response
```
And I got this on the command line:
```
{"id":"","message":"Unable to authenticate you."}
```
This is weird b/c I was creating droplets with my oauth v2 token not 30 minutes ago..

**Comment by science** [comment] 2015-03-18 21:30
This authentication issue isn't something as simple as my authentication token being bad. I am using droplet_kit to create servers immediately after getting that error message calling `client.droplets.all.any?`

So my oauth token *works* but your api is, in some cases, returning that error. Pretty weird. Any advice appreciated.

**Comment by phillbaker** [comment] 2015-03-18 22:34
@science thanks for the detail. If we can narrow down whether the issue is in the client or at the API level, that'd be helpful.

In addition to calling `client.droplets.all.any?`, can you try shelling out to curl, doing something like `curl -X GET -H 'Content-Type: application/json' -H 'Authorization: Bearer #{token}' "https://api.digitalocean.com/v2/droplets?page=1"`

Alternatively, if we can log the requests that Faraday is making under the hood, that'd also be good, let me see if I can throw a snippet together that would do that.

**Comment by science** [comment] 2015-03-18 23:29
Same error from the API - so it's not client side I think. I'm getting bad,
repeating timeout problems just creating new droplets from the API. One of
my developers said he was having droplets in the "new" state for 30 minutes
yesterday before they would finish. We also had some apt-get repo failures
pointing at your internal repo IP's - not sure if that's related..

I opened a ticket (#561720) about the droplet time out problem in your
support system too (just FYI). Thanks!
```
steve@Zorin-VM:~/devops/ansible$ ruby test.rb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
 Current
                                 Dload  Upload   Total   Spent    Left
 Speed
100    49    0    49    0     0     77      0 --:--:-- --:--:-- --:--:--
 77
{"id":"","message":"Unable to authenticate you."}
```
Code run:
```
require 'droplet_kit'
oauth = "[snip]"
puts `curl -X GET -H 'Content-Type: application/json' -H 'Authorization:
Bearer #{oauth}' "https://api.digitalocean.com/v2/droplets?page=1"`
```

**Comment by science** [comment] 2015-03-18 23:31
Should I try regenerating my oauth token? Not a lot of pain for me to do that..

**Comment by phillbaker** [comment] 2015-03-18 23:59
The slow droplet create, apt-get issues and API HTTP 401 responses are not likely related. We'll look into HTTP 401s and see if we can correlate anything across requests. Thanks for the additional data.

**Comment by phillbaker** [comment] 2015-03-19 12:19
@science what calls are you making immediately before the `droplets.all`?

**Comment by science** [comment] 2015-03-19 16:32
I just call `Client.new` - nothing else. It happens on `.find` and `.all.any?` or `.all.each`. Here's my current iteration of the code. I was able to `.create` some droplets yesterday using DropletKit (though the create timed out waiting on DO), so my oauth token appears to be working. 
```
require 'droplet_kit'
require 'byebug'
oauth = "[snip]"
x = DropletKit::Client.new(access_token: oauth)
#byebug
puts x.droplets.find(id: [snip])
```
Here's `bundle.list` but I'm not calling `bundle.setup` or `bundle.require` for this project so it shouldn't be including anything that DropletKit isn't including itself.. And it happens whether or not I comment out byebug. Note I'm not using RVM or rbenv so there are more gems available in my system (like byebug) than appear in `bundle.list`.
```
  * activesupport (4.1.9)
  * addressable (2.3.7)
  * axiom-types (0.1.1)
  * bundler (1.7.9)
  * coercible (1.0.0)
  * descendants_tracker (0.0.4)
  * droplet_kit (1.2.0)
  * equalizer (0.0.9)
  * faraday (0.9.1)
  * i18n (0.7.0)
  * ice_nine (0.11.1)
  * json (1.8.2)
  * kartograph (0.2.2)
  * mina (0.3.3)
  * minitest (5.5.1)
  * multipart-post (2.0.0)
  * open4 (1.3.4)
  * rake (10.4.2)
  * resource_kit (0.1.3)
  * slop (4.0.0)
  * thread_safe (0.3.5)
  * tzinfo (1.2.2)
  * virtus (1.0.5)
```

**Comment by science** [comment] 2015-03-19 16:33
I'm happy to private message you my oauth token or generate you another one for my account, if you want to see if it happens on my account for you?

**Comment by phillbaker** [comment] 2015-03-19 16:50
@science if you could email me at: phillip@digitalocean.com, that'd be great.

**Comment by science** [comment] 2015-03-20 01:04
I'm an idiot - Digital Ocean's API is working fine. I'd close this ticket except that is was already closed.. Sorry for the noise on this.

**Closed** 2015-03-20 01:10 UTC

**Comment by na-g** [comment] 2015-04-09 19:38
I ran into a similar issue and came here looking for answers.  The failure in my case was passing the options hash to Client.new with a string key, instead of a symbol. e.g. Client.new("access_token"=>"[my token]"), instead of Client.new(access_token:"[my token]").

**Comment by phillbaker** [comment] 2015-04-09 19:40
@na-g thanks! We'll get that fixed as well.

**Comment by andyw8** [comment] 2020-02-03 18:01
For anyone who encounters this thread from searching the error text – check the Digital Ocean status page for current API issues https://status.digitalocean.com/
