### ISSUE TITLE
Raise errors on all 422's

### ISSUE THREAD

**Issue by bobbytables** [digitalocean/droplet_kit#1] opened 2014-08-09 01:28 UTC

**Comment by brunomperes** [comment] 2015-09-23 21:35
I see the commit but it doesn't seem to be raising the errors (and the issue is open). Is is still under development?

**Comment by phillbaker** [comment] 2015-09-23 22:20
So it looks like #45 only addressed 422s on 2 endpoints, https://github.com/digitalocean/droplet_kit/pull/65 should handle non 20x responses everywhere.

**Comment by phillbaker** [comment] 2015-11-20 17:26
Closing as #65 is merged.

**Closed by phillbaker** 2015-11-20 17:26 UTC
